-- Choping: esquema inicial para Supabase PostgreSQL
-- Ejecutar completo en Supabase > SQL Editor.

create table if not exists stores (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  owner_name varchar(120),
  category varchar(80),
  city varchar(80),
  description text,
  rating numeric(2,1) not null default 4.5 check (rating between 0 and 5),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  store_id bigint not null references stores(id) on delete cascade,
  name varchar(120) not null,
  category varchar(80) not null,
  description text,
  story text,
  price numeric(14,2) not null check (price >= 0),
  image text,
  rating numeric(2,1) not null default 4.5 check (rating between 0 and 5),
  review text,
  likes integer not null default 0 check (likes >= 0),
  purchases integer not null default 0 check (purchases >= 0),
  created_at timestamptz not null default now()
);

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  image_url text not null,
  position smallint not null check (position between 1 and 3),
  unique(product_id, position)
);

insert into stores (name, owner_name, category, city, description, rating)
values
  ('Tech Zone', 'Equipo Tech Zone', 'Tecnologia', 'Bogota', 'Tecnologia para trabajar, estudiar y crear.', 4.9),
  ('Casa Viva', 'Equipo Casa Viva', 'Hogar', 'Medellin', 'Electrodomesticos practicos para el hogar.', 4.8),
  ('EcoRuedas', 'Equipo EcoRuedas', 'Movilidad', 'Barranquilla', 'Movilidad urbana electrica y sostenible.', 4.7)
on conflict do nothing;

insert into products (store_id, name, category, description, story, price, image, rating, review, likes, purchases)
select s.id, p.name, p.category, p.description, p.story, p.price, p.image, p.rating, p.review, p.likes, p.purchases
from (values
  ('Tech Zone','Combo PC Gamer TUF','Tecnologia','Computador gamer completo para jugar, estudiar y crear contenido.','Nacio para armar un setup completo en una sola compra.',3850000,4.8,'Excelente rendimiento para juegos competitivos y multitarea diaria.',248,37,'products/pc-gamer.png'),
  ('Casa Viva','Licuadora Ninja Pro','Hogar','Potencia para jugos, smoothies y preparaciones diarias.','Pensada para cocinas activas y desayunos rapidos.',420000,4.7,'Tritura muy bien y se siente firme con mezclas densas.',186,52,'products/licuadora-ninja.png'),
  ('Casa Viva','Lavadora semiautomatica 16 kg','Electrodomesticos','Gran capacidad y manejo practico para hogares familiares.','Hecha para resolver cargas grandes sin depender de lavanderias.',780000,4.5,'Buena capacidad, facil manejo y tamano conveniente.',121,29,'products/lavadora.png'),
  ('Tech Zone','Redmi Note 5G','Celulares','Pantalla amplia, camara multiple y bateria para todo el dia.','Un celular equilibrado para trabajar y mantenerse conectado.',1150000,4.9,'Pantalla nitida, buena autonomia y respuesta fluida.',312,84,'products/redmi.png'),
  ('EcoRuedas','Moto electrica urbana','Movilidad','Movilidad urbana con bajo consumo y manejo sencillo.','Creada para moverse por la ciudad con menos gasto.',4600000,4.6,'Practica para ciudad, silenciosa y economica.',204,18,'products/moto-electrica.png'),
  ('Casa Viva','Aspiradora compacta','Hogar','Limpieza practica para espacios pequenos y medianos.','Una ayuda simple para mantener cada ambiente en orden.',295000,4.6,'Ligera y practica para la limpieza diaria.',98,21,'products/licuadora-ninja.png'),
  ('Tech Zone','Teclado mecanico RGB','Tecnologia','Teclado mecanico iluminado para setups de trabajo y juego.','Un accesorio pensado para escribir y jugar con comodidad.',185000,4.7,'Respuesta agradable y buena iluminacion.',143,33,'products/pc-gamer.png'),
  ('EcoRuedas','Casco urbano certificado','Movilidad','Proteccion comoda y ligera para recorridos urbanos.','Seguridad esencial para moverse todos los dias.',210000,4.8,'Comodo, ligero y de buen ajuste.',87,16,'products/moto-electrica.png'),
  ('EcoRuedas','Bicicleta electrica urbana','Movilidad','Bicicleta electrica ligera para recorridos diarios por la ciudad.','Una alternativa practica para los trayectos cotidianos.',2800000,4.7,'Ligera y muy util para recorridos urbanos.',76,12,'products/moto-electrica.png')
) as p(store_name,name,category,description,story,price,rating,review,likes,purchases,image)
join stores s on s.name = p.store_name
where not exists (select 1 from products existing where existing.name = p.name);

insert into product_images (product_id, image_url, position)
select p.id, p.image, image_position
from products p
cross join lateral (values (1),(2),(3)) as positions(image_position)
left join product_images pi on pi.product_id = p.id and pi.position = positions.image_position
where pi.id is null;

create index if not exists products_store_id_idx on products(store_id);
create index if not exists products_category_idx on products(category);
create index if not exists product_images_product_id_idx on product_images(product_id);
